-- =====================================================
-- PATCH DATABASE CHO TRANSITGO LOCAL
-- Sửa lỗi thiếu cột do frontend gửi dữ liệu khác schema
-- =====================================================

-- ================= ROUTES =================
ALTER TABLE routes ADD COLUMN IF NOT EXISTS start_point VARCHAR(255);
ALTER TABLE routes ADD COLUMN IF NOT EXISTS end_point VARCHAR(255);
ALTER TABLE routes ADD COLUMN IF NOT EXISTS duration VARCHAR(100);
ALTER TABLE routes ADD COLUMN IF NOT EXISTS distance NUMERIC DEFAULT 0;
ALTER TABLE routes ADD COLUMN IF NOT EXISTS distance_km NUMERIC DEFAULT 0;
ALTER TABLE routes ADD COLUMN IF NOT EXISTS estimated_duration VARCHAR(100);
ALTER TABLE routes ADD COLUMN IF NOT EXISTS note TEXT;
ALTER TABLE routes ADD COLUMN IF NOT EXISTS status VARCHAR(50) DEFAULT 'active';
ALTER TABLE routes ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;

-- ================= BUS TYPES =================
ALTER TABLE bus_types ADD COLUMN IF NOT EXISTS seat_count INTEGER DEFAULT 0;
ALTER TABLE bus_types ADD COLUMN IF NOT EXISTS description TEXT;
ALTER TABLE bus_types ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE bus_types ALTER COLUMN seat_capacity DROP NOT NULL;

-- ================= BUSES =================
ALTER TABLE buses ADD COLUMN IF NOT EXISTS plate_number VARCHAR(50);
ALTER TABLE buses ADD COLUMN IF NOT EXISTS seat_count INTEGER DEFAULT 0;
ALTER TABLE buses ADD COLUMN IF NOT EXISTS brand VARCHAR(255);
ALTER TABLE buses ADD COLUMN IF NOT EXISTS note TEXT;
ALTER TABLE buses ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE buses ALTER COLUMN code DROP NOT NULL;
ALTER TABLE buses ALTER COLUMN license_plate DROP NOT NULL;
ALTER TABLE buses ALTER COLUMN seat_capacity DROP NOT NULL;

-- ================= BUS SEATS =================
ALTER TABLE bus_seats ADD COLUMN IF NOT EXISTS seat_type VARCHAR(50) DEFAULT 'normal';
ALTER TABLE bus_seats ADD COLUMN IF NOT EXISTS status VARCHAR(50) DEFAULT 'available';
ALTER TABLE bus_seats ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;

-- ================= DRIVERS =================
ALTER TABLE drivers ADD COLUMN IF NOT EXISTS note TEXT;
ALTER TABLE drivers ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE drivers ALTER COLUMN license_number DROP NOT NULL;

-- ================= CUSTOMERS =================
ALTER TABLE customers ADD COLUMN IF NOT EXISTS province VARCHAR(100);
ALTER TABLE customers ADD COLUMN IF NOT EXISTS district VARCHAR(100);
ALTER TABLE customers ADD COLUMN IF NOT EXISTS ward VARCHAR(100);
ALTER TABLE customers ADD COLUMN IF NOT EXISTS note TEXT;
ALTER TABLE customers ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE customers ALTER COLUMN name DROP NOT NULL;

-- ================= STATIONS =================
ALTER TABLE stations ADD COLUMN IF NOT EXISTS note TEXT;
ALTER TABLE stations ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;

-- ================= BUS STOPS =================
ALTER TABLE bus_stops ADD COLUMN IF NOT EXISTS note TEXT;
ALTER TABLE bus_stops ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;

-- ================= TRIPS =================
ALTER TABLE trips ADD COLUMN IF NOT EXISTS trip_code VARCHAR(100);
ALTER TABLE trips ADD COLUMN IF NOT EXISTS route_name VARCHAR(255);
ALTER TABLE trips ADD COLUMN IF NOT EXISTS bus_name VARCHAR(255);
ALTER TABLE trips ADD COLUMN IF NOT EXISTS driver_name VARCHAR(255);
ALTER TABLE trips ADD COLUMN IF NOT EXISTS price NUMERIC DEFAULT 0;
ALTER TABLE trips ADD COLUMN IF NOT EXISTS total_seats INTEGER DEFAULT 0;
ALTER TABLE trips ADD COLUMN IF NOT EXISTS booked_seats INTEGER DEFAULT 0;
ALTER TABLE trips ADD COLUMN IF NOT EXISTS start_time TIMESTAMP;
ALTER TABLE trips ADD COLUMN IF NOT EXISTS note TEXT;
ALTER TABLE trips ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE trips ALTER COLUMN code DROP NOT NULL;
ALTER TABLE trips ALTER COLUMN route_id DROP NOT NULL;
ALTER TABLE trips ALTER COLUMN departure_time DROP NOT NULL;

-- ================= BOOKINGS =================
ALTER TABLE bookings ADD COLUMN IF NOT EXISTS booking_code VARCHAR(100);
ALTER TABLE bookings ADD COLUMN IF NOT EXISTS passenger_name VARCHAR(255);
ALTER TABLE bookings ADD COLUMN IF NOT EXISTS passenger_phone VARCHAR(50);
ALTER TABLE bookings ADD COLUMN IF NOT EXISTS passenger_email VARCHAR(255);
ALTER TABLE bookings ADD COLUMN IF NOT EXISTS trip_code VARCHAR(100);
ALTER TABLE bookings ADD COLUMN IF NOT EXISTS route_name VARCHAR(255);
ALTER TABLE bookings ADD COLUMN IF NOT EXISTS total_amount NUMERIC DEFAULT 0;
ALTER TABLE bookings ADD COLUMN IF NOT EXISTS paid_amount NUMERIC DEFAULT 0;
ALTER TABLE bookings ADD COLUMN IF NOT EXISTS debt_amount NUMERIC DEFAULT 0;
ALTER TABLE bookings ADD COLUMN IF NOT EXISTS status VARCHAR(50) DEFAULT 'pending';
ALTER TABLE bookings ADD COLUMN IF NOT EXISTS note TEXT;
ALTER TABLE bookings ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE bookings ALTER COLUMN booking_code DROP NOT NULL;
ALTER TABLE bookings ALTER COLUMN trip_id DROP NOT NULL;
ALTER TABLE bookings ALTER COLUMN passenger_name DROP NOT NULL;
ALTER TABLE bookings ALTER COLUMN passenger_phone DROP NOT NULL;

-- ================= TICKETS =================
ALTER TABLE tickets ADD COLUMN IF NOT EXISTS ticket_code VARCHAR(100);
ALTER TABLE tickets ADD COLUMN IF NOT EXISTS passenger_name VARCHAR(255);
ALTER TABLE tickets ADD COLUMN IF NOT EXISTS passenger_phone VARCHAR(50);
ALTER TABLE tickets ADD COLUMN IF NOT EXISTS trip_code VARCHAR(100);
ALTER TABLE tickets ADD COLUMN IF NOT EXISTS seat_number VARCHAR(50);
ALTER TABLE tickets ADD COLUMN IF NOT EXISTS price NUMERIC DEFAULT 0;
ALTER TABLE tickets ADD COLUMN IF NOT EXISTS status VARCHAR(50) DEFAULT 'active';
ALTER TABLE tickets ADD COLUMN IF NOT EXISTS checked_in BOOLEAN DEFAULT false;
ALTER TABLE tickets ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE tickets ALTER COLUMN ticket_code DROP NOT NULL;
ALTER TABLE tickets ALTER COLUMN booking_id DROP NOT NULL;
ALTER TABLE tickets ALTER COLUMN trip_id DROP NOT NULL;
ALTER TABLE tickets ALTER COLUMN passenger_name DROP NOT NULL;

-- ================= PAYMENTS =================
ALTER TABLE payments ADD COLUMN IF NOT EXISTS payment_code VARCHAR(100);
ALTER TABLE payments ADD COLUMN IF NOT EXISTS booking_code VARCHAR(100);
ALTER TABLE payments ADD COLUMN IF NOT EXISTS passenger_name VARCHAR(255);
ALTER TABLE payments ADD COLUMN IF NOT EXISTS status VARCHAR(50) DEFAULT 'paid';
ALTER TABLE payments ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE payments ALTER COLUMN booking_id DROP NOT NULL;
ALTER TABLE payments ALTER COLUMN amount SET DEFAULT 0;

-- ================= REVIEWS =================
ALTER TABLE reviews ADD COLUMN IF NOT EXISTS customer_name VARCHAR(255);
ALTER TABLE reviews ADD COLUMN IF NOT EXISTS phone VARCHAR(50);
ALTER TABLE reviews ADD COLUMN IF NOT EXISTS content TEXT;
ALTER TABLE reviews ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;

-- ================= NOTIFICATIONS =================
ALTER TABLE notifications ADD COLUMN IF NOT EXISTS content TEXT;
ALTER TABLE notifications ADD COLUMN IF NOT EXISTS status VARCHAR(50) DEFAULT 'unread';
ALTER TABLE notifications ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE notifications ALTER COLUMN user_id DROP NOT NULL;
ALTER TABLE notifications ALTER COLUMN message DROP NOT NULL;

-- ================= MAINTENANCE =================
ALTER TABLE bus_maintenance ADD COLUMN IF NOT EXISTS note TEXT;
ALTER TABLE bus_maintenance ADD COLUMN IF NOT EXISTS maintenance_type VARCHAR(100);
ALTER TABLE bus_maintenance ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE bus_maintenance ALTER COLUMN bus_id DROP NOT NULL;

-- ================= SETTINGS =================
ALTER TABLE system_settings ADD COLUMN IF NOT EXISTS company_name VARCHAR(255);
ALTER TABLE system_settings ADD COLUMN IF NOT EXISTS phone VARCHAR(50);
ALTER TABLE system_settings ADD COLUMN IF NOT EXISTS email VARCHAR(255);
ALTER TABLE system_settings ADD COLUMN IF NOT EXISTS address TEXT;
ALTER TABLE system_settings ADD COLUMN IF NOT EXISTS tax_code VARCHAR(100);
ALTER TABLE system_settings ADD COLUMN IF NOT EXISTS note TEXT;
ALTER TABLE system_settings ADD COLUMN IF NOT EXISTS created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE system_settings ALTER COLUMN setting_key DROP NOT NULL;