-- =====================================================
-- TRANSITGO PATCH ALL - FIX LOCAL DEV SCHEMA
-- Chạy 1 lần để các trang admin thêm/sửa được dữ liệu
-- =====================================================

-- ================= BUS TYPES =================
ALTER TABLE bus_types ADD COLUMN IF NOT EXISTS type_name VARCHAR(255);
ALTER TABLE bus_types ADD COLUMN IF NOT EXISTS bus_type_name VARCHAR(255);
ALTER TABLE bus_types ADD COLUMN IF NOT EXISTS seat_count INTEGER DEFAULT 0;
ALTER TABLE bus_types ADD COLUMN IF NOT EXISTS seats INTEGER DEFAULT 0;
ALTER TABLE bus_types ADD COLUMN IF NOT EXISTS note TEXT;
ALTER TABLE bus_types ADD COLUMN IF NOT EXISTS status VARCHAR(50) DEFAULT 'active';

ALTER TABLE bus_types ALTER COLUMN name DROP NOT NULL;
ALTER TABLE bus_types ALTER COLUMN seat_capacity DROP NOT NULL;

-- ================= BUSES =================
ALTER TABLE buses ADD COLUMN IF NOT EXISTS plate_number VARCHAR(50);
ALTER TABLE buses ADD COLUMN IF NOT EXISTS bus_name VARCHAR(255);
ALTER TABLE buses ADD COLUMN IF NOT EXISTS name VARCHAR(255);
ALTER TABLE buses ADD COLUMN IF NOT EXISTS seat_count INTEGER DEFAULT 0;
ALTER TABLE buses ADD COLUMN IF NOT EXISTS seats INTEGER DEFAULT 0;
ALTER TABLE buses ADD COLUMN IF NOT EXISTS brand VARCHAR(255);
ALTER TABLE buses ADD COLUMN IF NOT EXISTS note TEXT;

ALTER TABLE buses ALTER COLUMN code DROP NOT NULL;
ALTER TABLE buses ALTER COLUMN license_plate DROP NOT NULL;
ALTER TABLE buses ALTER COLUMN seat_capacity DROP NOT NULL;

-- ================= BUS SEATS =================
ALTER TABLE bus_seats ADD COLUMN IF NOT EXISTS seat_code VARCHAR(50);
ALTER TABLE bus_seats ADD COLUMN IF NOT EXISTS seat_name VARCHAR(50);
ALTER TABLE bus_seats ADD COLUMN IF NOT EXISTS note TEXT;

ALTER TABLE bus_seats ALTER COLUMN bus_id DROP NOT NULL;
ALTER TABLE bus_seats ALTER COLUMN seat_number DROP NOT NULL;

-- ================= ROUTES =================
ALTER TABLE routes ADD COLUMN IF NOT EXISTS route_code VARCHAR(100);
ALTER TABLE routes ADD COLUMN IF NOT EXISTS route_name VARCHAR(255);
ALTER TABLE routes ADD COLUMN IF NOT EXISTS start_point VARCHAR(255);
ALTER TABLE routes ADD COLUMN IF NOT EXISTS end_point VARCHAR(255);
ALTER TABLE routes ADD COLUMN IF NOT EXISTS from_location VARCHAR(255);
ALTER TABLE routes ADD COLUMN IF NOT EXISTS to_location VARCHAR(255);
ALTER TABLE routes ADD COLUMN IF NOT EXISTS departure_station_name VARCHAR(255);
ALTER TABLE routes ADD COLUMN IF NOT EXISTS arrival_station_name VARCHAR(255);
ALTER TABLE routes ADD COLUMN IF NOT EXISTS distance_km NUMERIC DEFAULT 0;
ALTER TABLE routes ADD COLUMN IF NOT EXISTS estimated_time VARCHAR(100);
ALTER TABLE routes ADD COLUMN IF NOT EXISTS duration VARCHAR(100);
ALTER TABLE routes ADD COLUMN IF NOT EXISTS duration_minutes INTEGER DEFAULT 0;
ALTER TABLE routes ADD COLUMN IF NOT EXISTS note TEXT;

ALTER TABLE routes ALTER COLUMN code DROP NOT NULL;
ALTER TABLE routes ALTER COLUMN name DROP NOT NULL;

-- ================= ROUTE STOPS =================
ALTER TABLE route_stops ADD COLUMN IF NOT EXISTS route_name VARCHAR(255);
ALTER TABLE route_stops ADD COLUMN IF NOT EXISTS stop_name VARCHAR(255);
ALTER TABLE route_stops ADD COLUMN IF NOT EXISTS station_name VARCHAR(255);
ALTER TABLE route_stops ADD COLUMN IF NOT EXISTS name VARCHAR(255);
ALTER TABLE route_stops ADD COLUMN IF NOT EXISTS bus_stop_name VARCHAR(255);
ALTER TABLE route_stops ADD COLUMN IF NOT EXISTS address VARCHAR(255);
ALTER TABLE route_stops ADD COLUMN IF NOT EXISTS location VARCHAR(255);
ALTER TABLE route_stops ADD COLUMN IF NOT EXISTS sort_order INTEGER DEFAULT 0;
ALTER TABLE route_stops ADD COLUMN IF NOT EXISTS order_number INTEGER DEFAULT 0;
ALTER TABLE route_stops ADD COLUMN IF NOT EXISTS note TEXT;

ALTER TABLE route_stops ALTER COLUMN route_id DROP NOT NULL;
ALTER TABLE route_stops ALTER COLUMN stop_id DROP NOT NULL;
ALTER TABLE route_stops ALTER COLUMN stop_order DROP NOT NULL;

-- ================= STATIONS =================
ALTER TABLE stations ADD COLUMN IF NOT EXISTS note TEXT;
ALTER TABLE stations ALTER COLUMN name DROP NOT NULL;

-- ================= BUS STOPS =================
ALTER TABLE bus_stops ADD COLUMN IF NOT EXISTS note TEXT;
ALTER TABLE bus_stops ALTER COLUMN name DROP NOT NULL;

-- ================= DRIVERS =================
ALTER TABLE drivers ADD COLUMN IF NOT EXISTS note TEXT;
ALTER TABLE drivers ALTER COLUMN name DROP NOT NULL;
ALTER TABLE drivers ALTER COLUMN license_number DROP NOT NULL;

-- ================= STAFF =================
ALTER TABLE staff ADD COLUMN IF NOT EXISTS note TEXT;
ALTER TABLE staff ALTER COLUMN name DROP NOT NULL;

-- ================= CUSTOMERS =================
ALTER TABLE customers ADD COLUMN IF NOT EXISTS province VARCHAR(100);
ALTER TABLE customers ADD COLUMN IF NOT EXISTS district VARCHAR(100);
ALTER TABLE customers ADD COLUMN IF NOT EXISTS ward VARCHAR(100);
ALTER TABLE customers ADD COLUMN IF NOT EXISTS note TEXT;
ALTER TABLE customers ALTER COLUMN name DROP NOT NULL;

-- ================= TRIPS =================
ALTER TABLE trips ADD COLUMN IF NOT EXISTS trip_code VARCHAR(100);
ALTER TABLE trips ADD COLUMN IF NOT EXISTS route_name VARCHAR(255);
ALTER TABLE trips ADD COLUMN IF NOT EXISTS bus_name VARCHAR(255);
ALTER TABLE trips ADD COLUMN IF NOT EXISTS driver_name VARCHAR(255);
ALTER TABLE trips ADD COLUMN IF NOT EXISTS price NUMERIC DEFAULT 0;
ALTER TABLE trips ADD COLUMN IF NOT EXISTS total_seats INTEGER DEFAULT 0;
ALTER TABLE trips ADD COLUMN IF NOT EXISTS booked_seats INTEGER DEFAULT 0;
ALTER TABLE trips ADD COLUMN IF NOT EXISTS start_time TIMESTAMP;
ALTER TABLE trips ADD COLUMN IF NOT EXISTS note TEXT;

ALTER TABLE trips ALTER COLUMN code DROP NOT NULL;
ALTER TABLE trips ALTER COLUMN route_id DROP NOT NULL;
ALTER TABLE trips ALTER COLUMN departure_time DROP NOT NULL;

-- ================= BOOKINGS =================
ALTER TABLE bookings ADD COLUMN IF NOT EXISTS trip_code VARCHAR(100);
ALTER TABLE bookings ADD COLUMN IF NOT EXISTS route_name VARCHAR(255);
ALTER TABLE bookings ADD COLUMN IF NOT EXISTS paid_amount NUMERIC DEFAULT 0;
ALTER TABLE bookings ADD COLUMN IF NOT EXISTS debt_amount NUMERIC DEFAULT 0;
ALTER TABLE bookings ADD COLUMN IF NOT EXISTS status VARCHAR(50) DEFAULT 'pending';

ALTER TABLE bookings ALTER COLUMN booking_code DROP NOT NULL;
ALTER TABLE bookings ALTER COLUMN trip_id DROP NOT NULL;
ALTER TABLE bookings ALTER COLUMN passenger_name DROP NOT NULL;
ALTER TABLE bookings ALTER COLUMN passenger_phone DROP NOT NULL;

-- ================= TICKETS =================
ALTER TABLE tickets ADD COLUMN IF NOT EXISTS trip_code VARCHAR(100);
ALTER TABLE tickets ADD COLUMN IF NOT EXISTS seat_number VARCHAR(50);
ALTER TABLE tickets ADD COLUMN IF NOT EXISTS status VARCHAR(50) DEFAULT 'active';
ALTER TABLE tickets ADD COLUMN IF NOT EXISTS checked_in BOOLEAN DEFAULT false;

ALTER TABLE tickets ALTER COLUMN ticket_code DROP NOT NULL;
ALTER TABLE tickets ALTER COLUMN booking_id DROP NOT NULL;
ALTER TABLE tickets ALTER COLUMN trip_id DROP NOT NULL;
ALTER TABLE tickets ALTER COLUMN passenger_name DROP NOT NULL;

-- ================= PAYMENTS =================
ALTER TABLE payments ADD COLUMN IF NOT EXISTS payment_code VARCHAR(100);
ALTER TABLE payments ADD COLUMN IF NOT EXISTS booking_code VARCHAR(100);
ALTER TABLE payments ADD COLUMN IF NOT EXISTS passenger_name VARCHAR(255);
ALTER TABLE payments ADD COLUMN IF NOT EXISTS status VARCHAR(50) DEFAULT 'paid';

ALTER TABLE payments ALTER COLUMN booking_id DROP NOT NULL;
ALTER TABLE payments ALTER COLUMN amount DROP NOT NULL;

-- ================= REVIEWS =================
ALTER TABLE reviews ADD COLUMN IF NOT EXISTS customer_name VARCHAR(255);
ALTER TABLE reviews ADD COLUMN IF NOT EXISTS phone VARCHAR(50);
ALTER TABLE reviews ADD COLUMN IF NOT EXISTS content TEXT;

-- ================= NOTIFICATIONS =================
ALTER TABLE notifications ADD COLUMN IF NOT EXISTS content TEXT;
ALTER TABLE notifications ADD COLUMN IF NOT EXISTS status VARCHAR(50) DEFAULT 'unread';

ALTER TABLE notifications ALTER COLUMN user_id DROP NOT NULL;
ALTER TABLE notifications ALTER COLUMN title DROP NOT NULL;
ALTER TABLE notifications ALTER COLUMN message DROP NOT NULL;

-- ================= MAINTENANCE =================
ALTER TABLE bus_maintenance ALTER COLUMN bus_id DROP NOT NULL;
ALTER TABLE bus_maintenance ALTER COLUMN maintenance_date DROP NOT NULL;

-- ================= TRIP LOCATIONS =================
ALTER TABLE trip_locations ALTER COLUMN trip_id DROP NOT NULL;
ALTER TABLE trip_locations ALTER COLUMN latitude DROP NOT NULL;
ALTER TABLE trip_locations ALTER COLUMN longitude DROP NOT NULL;